### ISSUE TITLE
jshint doesn't use .jshintignore file

### ISSUE THREAD

**Issue by vkurup** [pre-commit/mirrors-jshint#6]
Does anyone have any success using a `.jshintignore` file to tell `jshint` to skip certain directories? If I run `jshint` directly (from the pre-commit cache directory), it sees the file, but if I run it from `pre-commit` it doesn't:

```
vkurup@caktus020:~/dev/myproject $ cat .jshintignore 
myproject/static/js/vendor/
vkurup@caktus020:~/dev/myproject $ ~/.cache/pre-commit/repoltl_i7v7/node_env-default/bin/jshint .
<Note: no output because no errors were found, since vendor directory was skipped>
vkurup@caktus020:~/dev/myproject $ pre-commit run -a jshint | tail
myproject/static/js/vendor/tinymce/plugins/visualchars/plugin.min.js: line 1, col 1223, Expected '!==' and instead saw '!='.
myproject/static/js/vendor/tinymce/plugins/visualchars/plugin.min.js: line 1, col 1254, Expected an assignment or function call and instead saw an expression.
myproject/static/js/vendor/tinymce/plugins/visualchars/plugin.min.js: line 1, col 1255, Missing semicolon.
myproject/static/js/vendor/tinymce/plugins/visualchars/plugin.min.js: line 1, col 1256, Expected an assignment or function call and instead saw an expression.
myproject/static/js/vendor/tinymce/plugins/visualchars/plugin.min.js: line 1, col 1257, Missing semicolon.
myproject/static/js/vendor/tinymce/plugins/visualchars/plugin.min.js: line 1, col 1, 'tinymce' is not defined.
myproject/static/js/vendor/tinymce/plugins/visualchars/plugin.min.js: line 1, col 466, 'tinymce' is not defined.

369 errors
```
Any tips or pointers would be much appreciated, thanks!

**Comment by asottile** [comment]
pre-commit will pass all filenames that match as positional arguments

my guess is `jshint` does not honor the exclusion in the `.jshintignore` if the filenames appear on the commandline

the recommendation is to use `pre-commit`'s `exclude: ` to limit which files are passed to the tool

it's also possible that `jshint` has some option that's like "no really I don't want those files" -- I know `black` and a few other tools have gained such options due to exactly what you're running into

**Comment by vkurup** [comment]
Thank you for the amazingly fast response! I did not know about the global `exclude:` directive. Adding `exclude: '^myproject/static/js/vendor/'` to the top of my file works perfectly.

Thanks again for pre-commit!
